import { Bar, BarChart, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertTriangle, BarChart3, PackageCheck, TrendingUp } from 'lucide-react';

type Row = { month: string; productionBags: number; distributionBags: number; salesRevenue: number; inventoryAvailable: number; shortages: number; wastageKg: number };
type Pareto = { name: string; value: number; percentage: number; cumulativePercentage: number };
type Analytics = { trends: Row[]; kpis: { completedBatches: number; totalBatches: number; rawMaterialKg: number; finishedFeedBags: number; availability: Record<string, number> }; productionPareto: Pareto[]; salesPareto: Pareto[]; forecast: { available: boolean; message?: string; target?: string; predictors?: string[]; historicalPeriods?: number; forecastBags?: number; forecastKg?: number; formulaName?: string | null; materials?: Array<{ name: string; inclusionPercentage: number | null; requiredKg: number | null }> } };
const n = (v: number) => new Intl.NumberFormat().format(v);
const money = (v: number) => `₱${n(v)}`;

function Trend({ title, field, rows, color }: { title: string; field: keyof Row; rows: Row[]; color: string }) {
    return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h4 className="text-xs font-bold uppercase tracking-wider text-slate-700">{title}</h4><div className="mt-4 h-52"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Bar dataKey={field} fill={color} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div>;
}
function ParetoPanel({ title, label, rows }: { title: string; label: string; rows: Pareto[] }) {
    return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h4 className="text-xs font-bold uppercase tracking-wider text-slate-700">{title}</h4><div className="mt-4 h-52"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" hide/><YAxis yAxisId="left" tick={{fontSize:10}}/><YAxis yAxisId="right" orientation="right" domain={[0,100]} tickFormatter={(v) => `${v}%`} tick={{fontSize:10}}/><Tooltip/><Bar yAxisId="left" dataKey="value" fill="#0f766e" radius={[4,4,0,0]}/><Line yAxisId="right" dataKey="cumulativePercentage" stroke="#f59e0b" strokeWidth={2}/></ComposedChart></ResponsiveContainer></div><table className="mt-3 w-full text-xs"><thead className="border-b text-left text-[10px] uppercase text-slate-400"><tr><th className="pb-2">{label === 'Bags' ? 'Feed product' : 'Customer'}</th><th className="text-right">{label}</th><th className="text-right">Share</th><th className="text-right">Cumulative</th></tr></thead><tbody>{rows.map(r => <tr className="border-b border-slate-100" key={r.name}><td className="py-2 font-medium">{r.name}</td><td className="text-right">{label === 'Revenue' ? money(r.value) : n(r.value)}</td><td className="text-right">{r.percentage.toFixed(2)}%</td><td className="text-right font-semibold text-teal-700">{r.cumulativePercentage.toFixed(2)}%</td></tr>)}</tbody></table>{!rows.length && <p className="py-3 text-xs text-slate-400">No completed records available.</p>}</div>;
}

export default function AnalyticsModule({ analytics }: { analytics?: Analytics }) {
    if (!analytics) return <div className="rounded-2xl border bg-white p-6 text-sm text-slate-500">Analytics data is unavailable.</div>;
    const { kpis, trends, forecast } = analytics; const completion = kpis.totalBatches ? kpis.completedBatches / kpis.totalBatches * 100 : 0;
    return <div className="space-y-6"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="flex items-center gap-2 text-sm font-black uppercase tracking-widest text-slate-800"><BarChart3 className="text-teal-600" size={18}/> Analytics Intelligence Hub</h3><p className="mt-2 text-xs text-slate-500">Descriptive trends, business intelligence, Pareto analysis, and database-derived forecasting.</p></div>
        <section><h4 className="mb-3 text-xs font-black uppercase tracking-widest text-slate-600">Business intelligence KPIs</h4><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-teal-700 p-5 text-white"><PackageCheck size={18}/><p className="mt-3 text-xs font-bold uppercase">Batch completion</p><p className="mt-1 text-2xl font-black">{n(kpis.completedBatches)} / {n(kpis.totalBatches)}</p><p className="text-xs text-teal-100">{completion.toFixed(1)}% completed</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase text-slate-600">Inventory levels</p><p className="mt-3 text-lg font-black">{n(kpis.rawMaterialKg)} kg raw</p><p className="text-xs text-slate-500">{n(kpis.finishedFeedBags)} finished-feed bags</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase text-slate-600">Stock availability</p><p className="mt-3 text-lg font-black">{kpis.availability.adequate} adequate</p><p className="text-xs text-slate-500">{kpis.availability.low} low · {kpis.availability.critical} critical · {kpis.availability.out} out</p></div></div></section>
        <section><h4 className="mb-3 text-xs font-black uppercase tracking-widest text-slate-600">Descriptive analytics</h4><div className="grid gap-5 lg:grid-cols-2"><Trend title="Production trends (bags)" field="productionBags" rows={trends} color="#0f766e"/><Trend title="Inventory trends (recorded availability)" field="inventoryAvailable" rows={trends} color="#2563eb"/><Trend title="Distribution trends (bags)" field="distributionBags" rows={trends} color="#0891b2"/><Trend title="Sales trends (PHP)" field="salesRevenue" rows={trends} color="#7c3aed"/><Trend title="Shortage trends (active alerts)" field="shortages" rows={trends} color="#dc2626"/><Trend title="Wastage trends (actual kg)" field="wastageKg" rows={trends} color="#ea580c"/></div>{!trends.length && <p className="mt-3 text-xs text-slate-400">No dated operational data is available.</p>}</section>
        <section className="grid gap-5 xl:grid-cols-2"><ParetoPanel title="Production Pareto" label="Bags" rows={analytics.productionPareto}/><ParetoPanel title="Customer Sales Pareto" label="Revenue" rows={analytics.salesPareto}/></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h4 className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-slate-700"><TrendingUp className="text-teal-600" size={16}/> Multiple linear regression forecast</h4>{forecast.available ? <><p className="mt-2 text-xs text-slate-500">Target: <b>{forecast.target}</b>. Predictors: {forecast.predictors?.join(' and ')}. Historical periods: {forecast.historicalPeriods}.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-teal-50 p-4"><p className="text-[10px] font-bold uppercase text-teal-700">Required production</p><p className="mt-1 text-2xl font-black text-teal-900">{n(forecast.forecastBags ?? 0)} bags</p><p className="text-xs text-teal-700">{n(forecast.forecastKg ?? 0)} kg</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase text-slate-500">Formulation used</p><p className="mt-1 font-bold">{forecast.formulaName ?? 'No recorded formulation'}</p></div></div><table className="mt-5 w-full text-xs"><thead className="border-b text-left text-[10px] uppercase text-slate-400"><tr><th className="pb-2">Raw material</th><th className="text-right">Inclusion %</th><th className="text-right">Estimated kg</th></tr></thead><tbody>{forecast.materials?.map(m => <tr className="border-b border-slate-100" key={m.name}><td className="py-2 font-medium">{m.name}</td><td className="text-right">{m.inclusionPercentage === null ? 'N/A' : `${m.inclusionPercentage.toFixed(2)}%`}</td><td className="text-right">{m.requiredKg === null ? 'N/A' : `${n(m.requiredKg)} kg`}</td></tr>)}</tbody></table></> : <div className="mt-4 flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800"><AlertTriangle size={16} className="shrink-0"/>{forecast.message}</div>}</section></div>;
}
