import React, { useState, useRef } from "react";
import { User, BackupRecord } from "../types";
import { 
  Database, Download, Upload, RefreshCw, ShieldCheck, 
  Clock, CheckCircle2, AlertTriangle, FileText, Trash2, 
  HardDrive, Server, Layers, Check, ArrowDownToLine
} from "lucide-react";

interface BackupRestoreModuleProps {
  currentUser: User;
  backups: BackupRecord[];
  onExecuteBackup: (type: "Full System Backup" | "User Registry Backup" | "Production & Inventory Backup", notes?: string) => void;
  onRestoreBackup: (backupData: any) => void;
  onDeleteBackup: (backupId: string) => void;
  fullDatabaseState: any;
}

export default function BackupRestoreModule({
  currentUser,
  backups,
  onExecuteBackup,
  onRestoreBackup,
  onDeleteBackup,
  fullDatabaseState
}: BackupRestoreModuleProps) {
  const [backupType, setBackupType] = useState<"Full System Backup" | "User Registry Backup" | "Production & Inventory Backup">("Full System Backup");
  const [notes, setNotes] = useState("");
  
  const [autoBackupEnabled, setAutoBackupEnabled] = useState(true);
  const [retentionDays, setRetentionDays] = useState(30);

  // File upload state for restore
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [uploadedBackupData, setUploadedBackupData] = useState<any | null>(null);
  const [showRestoreModal, setShowRestoreModal] = useState(false);
  const [restoreError, setRestoreError] = useState("");
  const [selectedHistorySnapshot, setSelectedHistorySnapshot] = useState<BackupRecord | null>(null);

  // Trigger JSON download
  const handleCreateAndDownloadJSON = () => {
    onExecuteBackup(backupType, notes || "Manual backup snapshot initiated by Super Admin");
    
    // Prepare JSON payload
    let downloadData = fullDatabaseState;
    if (backupType === "User Registry Backup") {
      downloadData = { users: fullDatabaseState.users, systemSettings: fullDatabaseState.systemSettings };
    } else if (backupType === "Production & Inventory Backup") {
      downloadData = { 
        rawMaterials: fullDatabaseState.rawMaterials, 
        feedProducts: fullDatabaseState.feedProducts,
        formulas: fullDatabaseState.formulas,
        productionBatches: fullDatabaseState.productionBatches 
      };
    }

    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(downloadData, null, 2));
    const downloadAnchor = document.createElement("a");
    const dateStr = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `feedchain_backup_${backupType.toLowerCase().replace(/ /g, "_")}_${dateStr}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();

    setNotes("");
    alert("Backup snapshot created and downloaded successfully.");
  };

  // Generate SQL dump format
  const handleExportSQLDump = () => {
    let sql = `-- FEEDCHAIN MySQL Relational Schema Dump\n`;
    sql += `-- Generated By: ${currentUser.firstName} ${currentUser.lastName} (${currentUser.role})\n`;
    sql += `-- Timestamp: ${new Date().toISOString()}\n\n`;

    // Users SQL
    sql += `-- Table: users\n`;
    sql += `CREATE TABLE IF NOT EXISTS users (id VARCHAR(20) PRIMARY KEY, first_name VARCHAR(100), last_name VARCHAR(100), email VARCHAR(100), role VARCHAR(50), status VARCHAR(20));\n`;
    fullDatabaseState.users.forEach((u: any) => {
      sql += `INSERT INTO users (id, first_name, last_name, email, role, status) VALUES ('${u.id}', '${u.firstName}', '${u.lastName}', '${u.email}', '${u.role}', '${u.status}');\n`;
    });

    // Feed products SQL
    sql += `\n-- Table: feed_products\n`;
    sql += `CREATE TABLE IF NOT EXISTS feed_products (code VARCHAR(20) PRIMARY KEY, name VARCHAR(100), price DECIMAL(10,2), quantity_bags INT, status VARCHAR(20));\n`;
    fullDatabaseState.feedProducts.forEach((fp: any) => {
      sql += `INSERT INTO feed_products (code, name, price, quantity_bags, status) VALUES ('${fp.code}', '${fp.name}', ${fp.price}, ${fp.quantityBags}, '${fp.status}');\n`;
    });

    const dataStr = "data:text/sql;charset=utf-8," + encodeURIComponent(sql);
    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `feedchain_mysql_dump_${new Date().toISOString().slice(0,10)}.sql`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  // File Upload Reader for Restore
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setRestoreError("");
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const parsed = JSON.parse(event.target?.result as string);
        if (!parsed || (typeof parsed !== "object")) {
          setRestoreError("Invalid JSON structure format.");
          return;
        }
        setUploadedBackupData(parsed);
        setShowRestoreModal(true);
      } catch (err) {
        setRestoreError("Failed to parse file. Make sure it is a valid JSON backup exported from FEEDCHAIN.");
      }
    };
    reader.readAsText(file);
  };

  const handleConfirmRestore = () => {
    if (!uploadedBackupData) return;
    onRestoreBackup(uploadedBackupData);
    setShowRestoreModal(false);
    setUploadedBackupData(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
    alert("Database restoration completed! All system tables have been synchronized to the uploaded snapshot.");
  };

  // Calculate storage stats
  const totalUsersCount = fullDatabaseState.users?.length || 0;
  const totalBatchesCount = fullDatabaseState.productionBatches?.length || 0;
  const totalProductsCount = fullDatabaseState.feedProducts?.length || 0;
  const totalMaterialsCount = fullDatabaseState.rawMaterials?.length || 0;

  return (
    <div className="space-y-6 font-sans select-none">
      
      {/* SYSTEM STORAGE & BACKUP STATUS */}
      <div className="bg-white border border-slate-200 p-6 rounded-2xl shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex items-start gap-4">
          <div className="p-3.5 bg-purple-50 text-purple-600 rounded-2xl border border-purple-100 shrink-0">
            <Server size={28} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-extrabold text-slate-800">System Database Backup & Disaster Recovery Center</h3>
              <span className="px-2.5 py-0.5 rounded-full text-[10px] font-extrabold bg-emerald-50 text-emerald-700 border border-emerald-100 flex items-center gap-1">
                <ShieldCheck size={12} />
                Encrypted Snapshot Protection
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-1 max-w-2xl leading-relaxed">
              Create offline encrypted database snapshots, export MySQL relation schemas, or restore full system records to prevent data loss across Davao del Sur facility operations.
            </p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-3 border-t md:border-t-0 md:border-l border-slate-100 pt-4 md:pt-0 md:pl-6 shrink-0">
          <button
            onClick={() => fileInputRef.current?.click()}
            className="bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs px-4 py-2.5 rounded-xl border border-slate-200 flex items-center gap-2 cursor-pointer transition-all"
          >
            <Upload size={14} className="text-purple-600" />
            Upload & Restore JSON
          </button>
          <input
            type="file"
            ref={fileInputRef}
            onChange={handleFileUpload}
            accept=".json"
            className="hidden"
          />

          <button
            onClick={handleExportSQLDump}
            className="bg-slate-900 hover:bg-slate-800 text-emerald-400 font-bold text-xs px-4 py-2.5 rounded-xl flex items-center gap-2 cursor-pointer transition-all shadow"
          >
            <Database size={14} />
            Export MySQL SQL Dump
          </button>
        </div>
      </div>

      {/* CREATE BACKUP GENERATOR CARD */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Generator Form */}
        <div className="lg:col-span-2 bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-4">
          <div className="flex items-center gap-2 pb-3 border-b border-slate-100">
            <HardDrive size={18} className="text-teal-600" />
            <h4 className="text-xs font-black uppercase text-slate-800 tracking-wider">Execute On-Demand Backup Snapshot</h4>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-1.5">Select Backup Scope</label>
              <select
                className="w-full bg-slate-50 border border-slate-200 text-xs font-semibold rounded-xl px-3.5 py-2.5 focus:ring-2 focus:ring-teal-500 focus:outline-none text-slate-700"
                value={backupType}
                onChange={(e: any) => setBackupType(e.target.value)}
              >
                <option value="Full System Backup">Full System Database Snapshot (All Tables)</option>
                <option value="User Registry Backup">User Accounts & Privilege Matrix Only</option>
                <option value="Production & Inventory Backup">Production Batches, Formulas & Inventories Only</option>
              </select>
            </div>

            <div>
              <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-1.5">Backup Note / Reference</label>
              <input
                type="text"
                className="w-full bg-slate-50 border border-slate-200 text-xs rounded-xl px-3.5 py-2.5 focus:ring-2 focus:ring-teal-500 focus:outline-none text-slate-700 placeholder-slate-400"
                placeholder="E.g. Pre-audit monthly closing snapshot"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
              />
            </div>
          </div>

          <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl flex items-center justify-between">
            <div className="space-y-0.5">
              <span className="text-xs font-bold text-slate-800">Include System Audit Logs & Active Settings</span>
              <p className="text-[11px] text-slate-400">Embed activity history and configuration policies inside the backup payload</p>
            </div>
            <span className="px-2.5 py-1 text-[10px] font-mono font-bold bg-teal-100 text-teal-800 rounded-md">JSON Structured</span>
          </div>

          <div className="pt-2 flex justify-end">
            <button
              onClick={handleCreateAndDownloadJSON}
              className="bg-teal-600 hover:bg-teal-500 text-white font-bold text-xs px-6 py-3 rounded-xl flex items-center gap-2 shadow-md cursor-pointer transition-all active:scale-98"
            >
              <Download size={15} />
              Generate & Download Backup File
            </button>
          </div>
        </div>

        {/* Database Health Summary */}
        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-4">
          <div className="flex items-center gap-2 pb-3 border-b border-slate-100">
            <Layers size={18} className="text-purple-600" />
            <h4 className="text-xs font-black uppercase text-slate-800 tracking-wider">Live Database Telemetry</h4>
          </div>

          <div className="space-y-3">
            <div className="flex justify-between items-center text-xs p-2.5 bg-slate-50 rounded-xl">
              <span className="text-slate-500 font-medium">Registered Accounts</span>
              <span className="font-mono font-bold text-slate-800">{totalUsersCount} records</span>
            </div>
            <div className="flex justify-between items-center text-xs p-2.5 bg-slate-50 rounded-xl">
              <span className="text-slate-500 font-medium">Feed Products & Formulas</span>
              <span className="font-mono font-bold text-slate-800">{totalProductsCount} records</span>
            </div>
            <div className="flex justify-between items-center text-xs p-2.5 bg-slate-50 rounded-xl">
              <span className="text-slate-500 font-medium">Production Batch Logs</span>
              <span className="font-mono font-bold text-slate-800">{totalBatchesCount} records</span>
            </div>
            <div className="flex justify-between items-center text-xs p-2.5 bg-slate-50 rounded-xl">
              <span className="text-slate-500 font-medium">Raw Materials Inventory</span>
              <span className="font-mono font-bold text-slate-800">{totalMaterialsCount} records</span>
            </div>
          </div>

          <div className="pt-2">
            <div className="flex items-center gap-2 text-[11px] text-emerald-700 bg-emerald-50 border border-emerald-100 p-3 rounded-xl">
              <CheckCircle2 size={16} className="shrink-0 text-emerald-600" />
              <span>Database state verified intact and ready for snapshot export.</span>
            </div>
          </div>
        </div>

      </div>

      {/* BACKUP HISTORY LOG TABLE */}
      <div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden">
        <div className="px-6 py-4.5 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
          <div>
            <h3 className="text-xs font-black text-slate-800 uppercase tracking-widest flex items-center gap-2">
              <Clock className="text-teal-600" size={16} />
              Backup History & Disaster Snapshots Registry
            </h3>
            <p className="text-[11px] text-slate-400 mt-0.5">List of historical system backup snapshots created by administrators</p>
          </div>
          <span className="text-[10px] font-bold text-slate-500 bg-slate-100 border px-2.5 py-0.5 rounded-full">
            {backups.length} archived backups
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200/60 text-[10px] text-slate-500 uppercase font-extrabold tracking-wider">
                <th className="py-3 px-6">Backup ID</th>
                <th className="py-3 px-6">File Name</th>
                <th className="py-3 px-6">Type</th>
                <th className="py-3 px-6">Timestamp</th>
                <th className="py-3 px-6">Size</th>
                <th className="py-3 px-6">Created By</th>
                <th className="py-3 px-6 text-center">Status</th>
                <th className="py-3 px-6 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {backups.length === 0 ? (
                <tr>
                  <td colSpan={8} className="py-10 text-center text-slate-400 text-xs">
                    No backup records found in local archive history.
                  </td>
                </tr>
              ) : (
                backups.map((bak) => (
                  <tr key={bak.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="py-3.5 px-6 font-mono font-bold text-slate-400">{bak.id}</td>
                    <td className="py-3.5 px-6 font-mono font-bold text-teal-700 flex items-center gap-1.5">
                      <FileText size={13} className="text-slate-400 shrink-0" />
                      {bak.fileName}
                    </td>
                    <td className="py-3.5 px-6">
                      <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-slate-100 text-slate-700">
                        {bak.type}
                      </span>
                    </td>
                    <td className="py-3.5 px-6 font-mono text-slate-500">{bak.timestamp}</td>
                    <td className="py-3.5 px-6 font-mono text-slate-600">{bak.sizeKb.toLocaleString()} KB</td>
                    <td className="py-3.5 px-6 text-slate-700 font-semibold">{bak.createdBy}</td>
                    <td className="py-3.5 px-6 text-center">
                      <span className="inline-flex items-center gap-1 px-2.5 py-0.5 text-[10px] font-extrabold rounded-full bg-emerald-50 text-emerald-700 border border-emerald-100">
                        <Check size={10} />
                        {bak.status}
                      </span>
                    </td>
                    <td className="py-3.5 px-6 text-right">
                      <div className="flex justify-end gap-2">
                        <button
                          onClick={() => onDeleteBackup(bak.id)}
                          className="p-1.5 hover:bg-rose-50 text-rose-500 hover:text-rose-700 rounded-lg transition-all"
                          title="Purge Archive Record"
                        >
                          <Trash2 size={13} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* RESTORE CONFIRMATION MODAL */}
      {showRestoreModal && uploadedBackupData && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white border border-slate-200 rounded-2xl shadow-2xl w-full max-w-md overflow-hidden">
            <div className="px-6 py-4 border-b border-slate-100 flex justify-between items-center bg-rose-50/50">
              <div className="flex items-center gap-2 text-rose-700">
                <AlertTriangle size={18} />
                <h3 className="text-xs font-black uppercase tracking-widest">
                  Confirm System Data Restoration
                </h3>
              </div>
              <button 
                onClick={() => setShowRestoreModal(false)}
                className="text-slate-400 hover:text-slate-700 rounded-lg p-1 text-xs font-bold"
              >
                ✕
              </button>
            </div>

            <div className="p-6 space-y-4">
              <div className="p-3.5 bg-rose-50 border border-rose-100 rounded-xl text-xs text-rose-800 leading-relaxed">
                <strong>Warning:</strong> Restoring database state will overwrite current in-memory local data tables with the records contained inside this uploaded snapshot.
              </div>

              <div className="space-y-2 bg-slate-50 p-4 rounded-xl border border-slate-200 text-xs font-mono">
                <div className="text-slate-500 font-bold uppercase text-[10px] mb-1">Detected Tables in Uploaded File:</div>
                {Object.keys(uploadedBackupData).map(key => (
                  <div key={key} className="flex justify-between items-center text-slate-700">
                    <span>{key}</span>
                    <span className="font-bold text-teal-600">
                      {Array.isArray(uploadedBackupData[key]) ? `${uploadedBackupData[key].length} records` : 'Object'}
                    </span>
                  </div>
                ))}
              </div>

              <div className="pt-2 flex justify-end gap-2.5">
                <button
                  type="button"
                  onClick={() => setShowRestoreModal(false)}
                  className="bg-slate-100 hover:bg-slate-200 text-slate-600 font-bold text-xs px-4 py-2.5 rounded-xl transition-all"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleConfirmRestore}
                  className="bg-rose-600 hover:bg-rose-500 text-white font-bold text-xs px-5 py-2.5 rounded-xl transition-all shadow-md flex items-center gap-1.5"
                >
                  <RefreshCw size={14} />
                  Overwrite & Restore State
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
